name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Package application
      run: mvn package

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t my-app:staging .

    - name: Tag Docker Image
      run: docker tag my-app:staging my-registry/my-app:staging

    - name: Push Docker Image
      run: docker push my-registry/my-app:staging

    - name: Deploy to Staging Server
      run: |
        ssh -o StrictHostKeyChecking=no user@staging-server "docker pull my-registry/my-app:staging && docker-compose -f docker-compose.staging.yml up -d"

  merge-to-main:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Merge staging into main
      run: |
        git checkout main
        git merge staging
        git push origin main
